"""empty message

Revision ID: dcb0deaf0191
Revises: 947c8315b071
Create Date: 2021-09-25 15:35:50.115254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb0deaf0191'
down_revision = '947c8315b071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic_path')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
